# Generated by Django 3.1.3 on 2022-01-04 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20220104_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_test',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='choice',
            name='content',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='course',
            field=models.ManyToManyField(related_name='questions', to='onlinecourse.Course'),
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ManyToManyField(related_name='choices', to='onlinecourse.Question'),
        ),
    ]
